"""trusted_tier

Revision ID: 098693c5d2b3
Revises: 2e09fa1a9b06
Create Date: 2026-06-17 12:49:15.688402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '098693c5d2b3'
down_revision: Union[str, None] = '2e09fa1a9b06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trusted_email_whitelist',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.add_column('access_codes', sa.Column('type', sa.String(), nullable=False, server_default='demo'))
    op.add_column('access_codes', sa.Column('note', sa.String(), nullable=True))
    op.add_column('charts', sa.Column('profile_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('charts', 'profile_html')
    op.drop_column('access_codes', 'note')
    op.drop_column('access_codes', 'type')
    op.drop_table('trusted_email_whitelist')
    # ### end Alembic commands ###
