"""add access_codes table

Revision ID: 2e09fa1a9b06
Revises: 521df26c536f
Create Date: 2026-06-15 19:36:49.414062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e09fa1a9b06'
down_revision: Union[str, None] = '521df26c536f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_codes',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('chart_id', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chart_id'], ['charts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_access_codes_chart_id'), 'access_codes', ['chart_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_access_codes_chart_id'), table_name='access_codes')
    op.drop_table('access_codes')
    # ### end Alembic commands ###
