"""initial schema

Revision ID: 521df26c536f
Revises: 
Create Date: 2026-06-13 20:48:45.470365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '521df26c536f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_bank',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tab', sa.String(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('click_count', sa.Integer(), nullable=False),
    sa.Column('lagna_filter', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_bank_tab'), 'question_bank', ['tab'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('google_id', sa.String(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('weekly_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('week_of', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_of')
    )
    op.create_table('charts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('birth_date', sa.String(), nullable=False),
    sa.Column('birth_time', sa.String(), nullable=False),
    sa.Column('birth_place', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('tz', sa.String(), nullable=False),
    sa.Column('chart_json', sa.JSON(), nullable=False),
    sa.Column('anon_slug', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anon_slug')
    )
    op.create_index(op.f('ix_charts_user_id'), 'charts', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chart_id', sa.String(), nullable=False),
    sa.Column('tab', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chart_id'], ['charts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_messages_chart_created', 'chat_messages', ['chart_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_chart_id'), 'chat_messages', ['chart_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_chart_id'), table_name='chat_messages')
    op.drop_index('ix_chat_messages_chart_created', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_charts_user_id'), table_name='charts')
    op.drop_table('charts')
    op.drop_table('weekly_questions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_question_bank_tab'), table_name='question_bank')
    op.drop_table('question_bank')
    # ### end Alembic commands ###
